# Generated by Django 6.0.5 on 2026-07-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom de la prestation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_unite', models.CharField(choices=[('M2', 'Au mètre carré (m²)'), ('LOT_100', 'Par lot de 100 flyers'), ('LETTRE', 'À la lettre / Autocollant')], default='M2', max_length=10, verbose_name='Type de calcul')),
                ('prix_unitaire', models.IntegerField(verbose_name='Prix unitaire (FCFA)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prestations/', verbose_name='Image du produit')),
            ],
        ),
    ]
