# Generated by Django 6.0.5 on 2026-08-09 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('email_client', models.EmailField(max_length=254)),
                ('telephone', models.CharField(default='', max_length=20)),
                ('adresse', models.TextField()),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('RECU', 'Commande reçue'), ('PREP', 'En cours de préparation'), ('EXPE', 'Expédiée'), ('LIVR', 'Livrée')], default='RECU', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('details_json', models.TextField(verbose_name='Détails de la commande (JSON)')),
                ('total_brut', models.IntegerField(default=0)),
                ('montant_remise', models.IntegerField(default=0)),
                ('total_final', models.IntegerField(default=0)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Bon validé / En cours'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20)),
                ('validee_par_client', models.BooleanField(default=False, verbose_name='Validé par le client')),
                ('bl_genere', models.BooleanField(default=False, verbose_name='Transféré en Bon de Livraison')),
                ('livre_par', models.CharField(default='Nous-mêmes', max_length=100, verbose_name='Livré par')),
            ],
        ),
        migrations.CreateModel(
            name='FormatFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_format', models.CharField(help_text='Ex: Format A5, Format A6', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flyers/')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom de la prestation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_unite', models.CharField(choices=[('SURFACE', 'Au mètre carré (Bâche, Vinyle, Affiche)'), ('FLYER', 'Lots & Paliers par Format (Flyer, Dépliant, Carte)'), ('UNITE', "À l'unité simple (Roll-up, Goodies, Reliure)"), ('PAGES', 'Au document multipage (Brochure, Catalogue)')], default='UNITE', max_length=10, verbose_name='Type de calcul')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prestations/', verbose_name='Image du produit')),
                ('remise_custom', models.IntegerField(default=0, verbose_name='Remise sur-mesure (%)')),
            ],
            options={
                'db_table': 'shop_prestation',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancien_prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('stock', models.PositiveIntegerField(default=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=150, verbose_name='Nom complet du client')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (optionnel)')),
                ('description_prestation', models.TextField(verbose_name='Détails des prestations demandées')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Total (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('numero_bl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de BL associé')),
                ('numero_devis_personnalise', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé au client'), ('valide', 'Validé par le client'), ('rejete', 'Rejeté'), ('converti_bl', 'Converti en BL')], default='brouillon', max_length=20)),
                ('livre_par', models.CharField(default='Nous-mêmes', max_length=150, verbose_name='Mode de livraison')),
                ('cree_par', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DevisAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devis_ref', models.CharField(max_length=20, verbose_name='Référence Devis')),
                ('client', models.CharField(max_length=150, verbose_name='Nom du Client')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Total')),
                ('statut_devis', models.CharField(max_length=50, verbose_name='État du devis')),
                ('action', models.CharField(choices=[('SUPPRESSION', 'Suppression validée'), ('TENTATIVE', 'Tentative de suppression')], max_length=20)),
                ('resultat', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('execute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': "Log d'Audit Devis",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total_bl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_recu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('mode_paiement', models.CharField(choices=[('WAVE', 'Wave 🌊'), ('OM', 'Orange Money 🍊'), ('MTN', 'MTN MoMo 💛'), ('CASH', 'Espèces 💵'), ('VIREMENT', 'Virement bancaire 🏦')], max_length=20)),
                ('statut_paiement', models.CharField(choices=[('PAYEE', 'Soldée / Payée ✅'), ('PARTIEL', 'Partiellement payée ⚠️')], default='PAYEE', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('devis_associe', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='shop.devis')),
            ],
        ),
        migrations.CreateModel(
            name='MessageAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('est_assistant', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionQuantiteFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité (ex: 100, 500)')),
                ('prix_total', models.IntegerField(help_text='Plus simple pour intégrer directement la dégressivité sans calcul complexe', verbose_name='Prix total pour ce lot (FCFA)')),
                ('remise_pourcentage', models.IntegerField(default=0, verbose_name='Remise en %')),
                ('format_flyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_quantite', to='shop.formatflyer')),
            ],
        ),
        migrations.CreateModel(
            name='PalierPrixUnitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_minimale', models.IntegerField(verbose_name='Quantité minimale')),
                ('prix_unitaire', models.IntegerField(verbose_name='Prix unitaire (FCFA)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='paliers/', verbose_name='Image du palier')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers_unite', to='shop.prestation')),
            ],
            options={
                'ordering': ['quantite_minimale'],
            },
        ),
        migrations.CreateModel(
            name='GrilleTarifaireSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(help_text='Ex: 1x1m, 2x3m, A0', max_length=50)),
                ('surface_m2', models.FloatField(verbose_name='Surface en m²')),
                ('prix_total', models.IntegerField(verbose_name='Prix total (FCFA)')),
                ('remise_pourcentage', models.IntegerField(default=0, verbose_name='Remise catalogue (%)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='surfaces/')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_surface', to='shop.prestation')),
            ],
        ),
        migrations.CreateModel(
            name='GrilleCataloguePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pages', models.IntegerField(verbose_name='Nombre de pages (Ex: 8, 12, 16)')),
                ('quantite', models.IntegerField(verbose_name="Quantité d'exemplaires")),
                ('prix_total', models.IntegerField(verbose_name='Prix total (FCFA)')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers_pages', to='shop.prestation')),
            ],
            options={
                'ordering': ['nombre_pages', 'quantite'],
            },
        ),
        migrations.AddField(
            model_name='formatflyer',
            name='prestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats_flyer', to='shop.prestation'),
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom de la réalisation (ex: Bâche Pro)')),
                ('commentaire', models.CharField(max_length=255, verbose_name='Texte accrocheur (ex: Qualité Premium YaTout)')),
                ('image', models.ImageField(upload_to='realisations/', verbose_name='Photo du rendu réel')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('prestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='shop.prestation')),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('devise', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar US ($)'), ('MAD', 'Dirham Marocain (DH)'), ('XOF', 'F cfa '), ('CAD', 'Dollar Canadien ($CA)')], default='EUR', max_length=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='shop.vendeur'),
        ),
    ]
