# Generated by Django 6.0.5 on 2026-08-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100, verbose_name='Nom ou Entreprise')),
                ('commentaire', models.TextField(verbose_name='Avis client')),
                ('note', models.IntegerField(default=5, verbose_name='Note sur 5')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_approuve', models.BooleanField(default=False, verbose_name='Afficher sur le site')),
            ],
        ),
    ]
