# Generated by Django 6.0.5 on 2026-06-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
