# Generated by Django 6.0.5 on 2026-09-18 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_temoignage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFaconnage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom du service (Ex: Reliure Document, Photocopie A4)')),
                ('description', models.TextField(blank=True)),
                ('prix_fixe_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix fixe à la page ou à l'acte")),
                ('remise_globale', models.IntegerField(default=0, verbose_name='Remise sur cet article (%)')),
            ],
            options={
                'db_table': 'print_faconnage',
            },
        ),
        migrations.CreateModel(
            name='SupportFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom du support (Ex: Flyers Standard, Cartes de Visite)')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prestations/flyers/')),
                ('remise_globale', models.IntegerField(default=0, verbose_name='Remise sur cet article (%)')),
            ],
            options={
                'db_table': 'print_flyer',
            },
        ),
        migrations.CreateModel(
            name='SupportGrandFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom du produit (Ex: Bâche Publicitaire, Vinyle)')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prestations/grand_format/')),
                ('prix_au_metre_carre', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base au M²')),
                ('remise_globale', models.IntegerField(default=0, verbose_name='Remise sur cet article (%)')),
            ],
            options={
                'db_table': 'print_grand_format',
            },
        ),
        migrations.CreateModel(
            name='SupportObjetPublicitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Nom de l'objet (Ex: Mug en Céramique, T-shirt)")),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prestations/goodies/')),
                ('remise_globale', models.IntegerField(default=0, verbose_name='Remise sur cet article (%)')),
            ],
            options={
                'db_table': 'print_objet',
            },
        ),
        migrations.CreateModel(
            name='PalierPrixObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_minimale', models.IntegerField(help_text="Ex: 1, 10, 50, 100 (S'applique à partir de ce volume)")),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix pour une seule pièce à ce palier', max_digits=10)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers_prix', to='shop.supportobjetpublicitaire')),
            ],
        ),
        migrations.CreateModel(
            name='TarifOptionFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_papier', models.CharField(help_text='Ex: A5, A6, 8.5x5.4cm', max_length=50)),
                ('quantite', models.IntegerField(help_text='Ex: 100, 500, 1000')),
                ('prix_total_lot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix brut global du lot')),
                ('flyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_specifiques', to='shop.supportflyer')),
            ],
        ),
    ]
