# Generated by Django 6.0.5 on 2026-06-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_produit_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('RECU', 'Commande reçue'), ('PREP', 'En cours de préparation'), ('EXPE', 'Expédiée'), ('LIVR', 'Livrée')], default='RECU', max_length=4),
        ),
    ]
