# Generated by Django 6.0.5 on 2026-09-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_servicefaconnage_supportflyer_supportgrandformat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionquantiteflyer',
            name='format_flyer',
        ),
        migrations.RemoveField(
            model_name='grillecataloguepages',
            name='prestation',
        ),
        migrations.RemoveField(
            model_name='grilletarifairesurface',
            name='prestation',
        ),
        migrations.RemoveField(
            model_name='palierprixunitaire',
            name='prestation',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='prestation',
        ),
        migrations.AddField(
            model_name='commandeimpression',
            name='numero_tombola',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='Numéro de tombola'),
        ),
        migrations.AlterField(
            model_name='palierprixobjet',
            name='quantite_minimale',
            field=models.IntegerField(help_text='Ex: 1, 10, 50, 100'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='commentaire',
            field=models.CharField(max_length=255, verbose_name='Texte accrocheur'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Nom de la réalisation'),
        ),
        migrations.CreateModel(
            name='TirageTombola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(unique=True, verbose_name='Mois du tirage')),
                ('date_tirage', models.DateTimeField(auto_now_add=True, verbose_name='Date du tirage')),
                ('commande_gagnante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tirages_gagnes', to='shop.commandeimpression', verbose_name='Commande gagnante')),
            ],
        ),
        migrations.DeleteModel(
            name='FormatFlyer',
        ),
        migrations.DeleteModel(
            name='OptionQuantiteFlyer',
        ),
        migrations.DeleteModel(
            name='GrilleCataloguePages',
        ),
        migrations.DeleteModel(
            name='GrilleTarifaireSurface',
        ),
        migrations.DeleteModel(
            name='PalierPrixUnitaire',
        ),
        migrations.DeleteModel(
            name='Prestation',
        ),
    ]
