# Generated by Django 6.0.5 on 2026-06-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
