# Generated by Django 6.0.5 on 2026-06-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_produit_devise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='devise',
        ),
        migrations.AddField(
            model_name='vendeur',
            name='devise',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar US ($)'), ('MAD', 'Dirham Marocain (DH)'), ('XOF', 'Franc CFA (FCFA)'), ('CAD', 'Dollar Canadien ($CA)')], default='EUR', max_length=3),
        ),
    ]
