# Generated by Django 6.0.5 on 2026-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_produit_devise_vendeur_devise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='devise',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar US ($)'), ('MAD', 'Dirham Marocain (DH)'), ('XOF', 'F cfa '), ('CAD', 'Dollar Canadien ($CA)')], default='EUR', max_length=3),
        ),
    ]
