# Generated by Django 6.0.5 on 2026-06-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_commande_produit_remove_commande_quantite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='ancien_prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
