# Generated by Django 6.0.5 on 2026-06-15 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_messageassistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom de la prestation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (€)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prestations/')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('details_options', models.TextField(blank=True, verbose_name='Options demandées')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Bon généré / En cours'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20)),
                ('remise_appliquee', models.BooleanField(default=False, verbose_name='Remise de 5% appliquée')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.prestation', verbose_name='Prestation demandée')),
            ],
        ),
    ]
