# Generated by Django 6.0.5 on 2026-06-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_prestation_commandeimpression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeimpression',
            name='details_options',
        ),
        migrations.RemoveField(
            model_name='commandeimpression',
            name='prestation',
        ),
        migrations.RemoveField(
            model_name='commandeimpression',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='commandeimpression',
            name='remise_appliquee',
        ),
        migrations.AddField(
            model_name='commandeimpression',
            name='details_json',
            field=models.TextField(default='[]', verbose_name='Détails de la commande (JSON)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandeimpression',
            name='montant_remise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandeimpression',
            name='remise_active',
            field=models.BooleanField(default=True, verbose_name='Remise de 5% appliquée'),
        ),
        migrations.AddField(
            model_name='commandeimpression',
            name='total_brut',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandeimpression',
            name='total_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commandeimpression',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Bon validé / En cours'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prestations/', verbose_name='Image du produit'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='prix_unitaire',
            field=models.IntegerField(verbose_name='Prix unitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Nom de la prestation (ex: Bâche, T-shirt)'),
        ),
    ]
