# Generated by Django 6.0.5 on 2026-06-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_commandeimpression_details_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='type_unite',
            field=models.CharField(choices=[('M2', 'Au mètre carré (m²)'), ('LOT_100', 'Par lot de 100 flyers'), ('LETTRE', 'À la lettre / Autocollant')], default='M2', max_length=10, verbose_name='Type de calcul'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Nom de la prestation'),
        ),
    ]
