# Generated by Django 6.0.5 on 2026-06-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_prestation_type_unite_alter_prestation_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeimpression',
            name='bl_genere',
            field=models.BooleanField(default=False, verbose_name='Transféré en Bon de Livraison'),
        ),
        migrations.AddField(
            model_name='commandeimpression',
            name='validee_par_client',
            field=models.BooleanField(default=False, verbose_name='Validé par le client'),
        ),
    ]
