# Generated by Django 6.0.5 on 2026-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_commandeimpression_bl_genere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom de la réalisation (ex: Bâche Pro)')),
                ('commentaire', models.CharField(max_length=255, verbose_name='Texte accrocheur (ex: Qualité Premium YaTout)')),
                ('image', models.ImageField(upload_to='realisations/', verbose_name='Photo du rendu réel')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
