# Generated by Django 6.0.5 on 2026-06-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_importer_prestations_initiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='type_unite',
            field=models.CharField(choices=[('M2', 'Au mètre carré (m²)'), ('UNITE', "À l'unité (Quantité × Prix)"), ('LOT_100', 'Par lot de 100 flyers'), ('LETTRE', 'À la lettre / Autocollant')], default='M2', max_length=10, verbose_name='Type de calcul'),
        ),
        migrations.AlterModelTable(
            name='prestation',
            table='shop_prestation',
        ),
    ]
