# Generated by Django 6.0.5 on 2026-07-11 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_prestation_type_unite_alter_prestation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeimpression',
            name='remise_active',
        ),
        migrations.RemoveField(
            model_name='prestation',
            name='prix_unitaire',
        ),
        migrations.AlterField(
            model_name='prestation',
            name='type_unite',
            field=models.CharField(choices=[('SURFACE', 'Au mètre carré (Bâche, Vinyle, Affiche)'), ('FLYER', 'Lots & Paliers par Format (Flyer, Dépliant, Carte)'), ('UNITE', "À l'unité simple (Roll-up, Goodies, Reliure)"), ('PAGES', 'Au document multipage (Brochure, Catalogue)')], default='UNITE', max_length=10, verbose_name='Type de calcul'),
        ),
        migrations.CreateModel(
            name='FormatFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_format', models.CharField(help_text='Ex: Format A5, Format A6, Standard (Carte)', max_length=50)),
                ('prix_unitaire', models.IntegerField(verbose_name='Prix unitaire de base (FCFA)')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats_flyer', to='shop.prestation')),
            ],
        ),
        migrations.CreateModel(
            name='GrilleTarifaireSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(help_text='Ex: 1x1m, 2x3m, A0', max_length=50)),
                ('surface_m2', models.FloatField(verbose_name='Surface en m²')),
                ('prix_total', models.IntegerField(verbose_name='Prix total pour cette dimension (FCFA)')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_surface', to='shop.prestation')),
            ],
        ),
    ]
