# Generated by Django 6.0.5 on 2026-07-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_commandeimpression_remise_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='shop.prestation'),
        ),
    ]
