# Generated by Django 6.0.5 on 2026-07-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_realisation_prestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatflyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flyers/', verbose_name='Image du format'),
        ),
        migrations.AddField(
            model_name='grilletarifairesurface',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='surfaces/', verbose_name='Image de démonstration'),
        ),
    ]
