# Generated by Django 6.0.5 on 2026-07-12 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_formatflyer_image_grilletarifairesurface_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionQuantite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(help_text='Ex: 100, 200, 500', verbose_name='Quantité (exemples)')),
                ('remise_pourcentage', models.IntegerField(default=0, verbose_name='Remise en %')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_quantite', to='shop.prestation')),
            ],
        ),
        migrations.CreateModel(
            name='PalierPrixUnitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_minimale', models.IntegerField(help_text='Ex: 1, 10, 50, 100', verbose_name='Quantité minimale')),
                ('prix_unitaire', models.IntegerField(verbose_name='Prix unitaire pour ce palier (FCFA)')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers_unite', to='shop.prestation')),
            ],
            options={
                'ordering': ['quantite_minimale'],
            },
        ),
    ]
