# Generated by Django 6.0.5 on 2026-07-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_palierprixunitaire_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionquantite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lots_flyers/', verbose_name='Image spécifique du lot'),
        ),
        migrations.AlterField(
            model_name='optionquantite',
            name='quantite',
            field=models.IntegerField(verbose_name='Quantité (exemples)'),
        ),
    ]
