# Generated by Django 6.0.5 on 2026-07-19 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_optionquantite_image_alter_optionquantite_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatflyer',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='palierprixunitaire',
            name='image',
        ),
        migrations.AddField(
            model_name='grilletarifairesurface',
            name='remise_pourcentage',
            field=models.IntegerField(default=0, verbose_name='Remise catalogue (%)'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='remise_custom',
            field=models.IntegerField(default=0, help_text='Pourcentage de réduction pour calculs libres.', verbose_name='Remise sur-mesure (%)'),
        ),
        migrations.AlterField(
            model_name='formatflyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flyers/'),
        ),
        migrations.AlterField(
            model_name='formatflyer',
            name='nom_format',
            field=models.CharField(help_text='Ex: Format A5, Format A6', max_length=50),
        ),
        migrations.AlterField(
            model_name='grilletarifairesurface',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='surfaces/'),
        ),
        migrations.AlterField(
            model_name='grilletarifairesurface',
            name='prix_total',
            field=models.IntegerField(verbose_name='Prix total (FCFA)'),
        ),
        migrations.AlterField(
            model_name='palierprixunitaire',
            name='prix_unitaire',
            field=models.IntegerField(verbose_name='Prix unitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='palierprixunitaire',
            name='quantite_minimale',
            field=models.IntegerField(verbose_name='Quantité minimale'),
        ),
        migrations.CreateModel(
            name='GrilleCataloguePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pages', models.IntegerField(verbose_name='Nombre de pages (Ex: 8, 12, 16)')),
                ('quantite', models.IntegerField(verbose_name="Quantité d'exemplaires")),
                ('prix_total', models.IntegerField(verbose_name='Prix total (FCFA)')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers_pages', to='shop.prestation')),
            ],
            options={
                'ordering': ['nombre_pages', 'quantite'],
            },
        ),
        migrations.CreateModel(
            name='OptionQuantiteFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité (ex: 100, 500)')),
                ('prix_total', models.IntegerField(help_text='Plus simple pour intégrer directement la dégressivité sans calcul complexe', verbose_name='Prix total pour ce lot (FCFA)')),
                ('remise_pourcentage', models.IntegerField(default=0, verbose_name='Remise en %')),
                ('format_flyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_quantite', to='shop.formatflyer')),
            ],
        ),
        migrations.DeleteModel(
            name='OptionQuantite',
        ),
    ]
