# Generated by Django 6.0.5 on 2026-07-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_formatflyer_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palierprixunitaire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='paliers/', verbose_name='Image du palier'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='remise_custom',
            field=models.IntegerField(default=0, verbose_name='Remise sur-mesure (%)'),
        ),
    ]
