# Generated by Django 6.0.5 on 2026-07-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_palierprixunitaire_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeimpression',
            name='livre_par',
            field=models.CharField(default='Nous-mêmes', max_length=100, verbose_name='Livré par'),
        ),
    ]
