# Generated by Django 6.0.5 on 2026-07-30 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_commandeimpression_livre_par'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=150, verbose_name='Nom complet du client')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (optionnel)')),
                ('description_prestation', models.TextField(verbose_name='Détails des prestations demandées')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Total (FCFA)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé au client'), ('valide', 'Validé par le client'), ('rejete', 'Rejeté'), ('converti_bl', 'Converti en BL')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('numero_bl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de BL associé')),
                ('cree_par', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
    ]
