# Generated by Django 6.0.5 on 2026-07-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='numero_devis_personnalise',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
